/**
 * Types for tool status generation
 */

import { ToolCall } from "@langchain/core/messages/tool";

/**
 * Tool status message generated by GPT-3.5-turbo
 */
export interface ToolStatusMessage {
  toolCallId: string;
  toolName: string;
  userFriendlyAction: string;
  estimatedDuration: string;
  timestamp: string;
}

/**
 * Status generation prompt data
 */
export interface StatusGenerationPrompt {
  toolName: string;
  toolParameters: Record<string, any>;
}

/**
 * Estimated duration categories
 */
export type EstimatedDuration =
  | "a few seconds"
  | "5-10 seconds"
  | "10-30 seconds"
  | "about a minute"
  | "1-2 minutes";

/**
 * Tool call with metadata for status generation
 */
export interface ToolCallWithMetadata {
  id: string;
  name: string;
  args: Record<string, any>;
}
